name: raa_pdm
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  provider: ^6.1.1
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6
  sqflite: ^2.3.0
  path: ^1.8.3
  firebase_ui_auth: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true